---
name: Lint

on:
  pull_request:
    paths:
      - "**.py"
  push:
    paths:
      - "**.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/ruff-action@v3.6.1
